<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions      
    name="ImitationService"    
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://otr.ru/nzx/ImitationService" 
    targetNamespace="http://otr.ru/nzx/ImitationService">

    <wsdl:message name="imitationRequest">
        <wsdl:part name="data" type="xs:string"/>
    </wsdl:message>
    <wsdl:message name="imitationResponse">
        <wsdl:part name="data" type="xs:string"/>
    </wsdl:message>
    
    <wsdl:portType name="ImitationServicePortType">
        <wsdl:operation name="sendData">
            <wsdl:input message="tns:imitationRequest" name="imitationRequest"/>
            <wsdl:output message="tns:imitationResponse" name="imitationResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="ImitationServiceBinding" type="tns:ImitationServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"></soap:binding>
        <wsdl:operation name="sendData">
            <soap:operation soapAction="sendData"></soap:operation>
            <wsdl:input>
                <soap:body use="literal"></soap:body>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"></soap:body>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="ImitationService">
        <wsdl:port binding="tns:ImitationServiceBinding" name="ImitationServicePort">
            <soap:address location="http://localhost:8088/ImitationService"></soap:address>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>

